LightningDesignApp::Application.routes.draw do
  match '/activity_timeline', to: 'components#activity_timeline', via: 'get'
  match '/badges', to: 'components#badges', via: 'get'
  match '/breadcrumbs', to: 'components#breadcrumbs', via: 'get'
  match '/buttons', to: 'components#buttons', via: 'get'
  match '/button_groups', to: 'components#button_groups', via: 'get'
  match '/cards', to: 'components#cards', via: 'get'
  match '/data_tables', to: 'components#data_tables', via: 'get'
  match '/datepickers', to: 'components#datepickers', via: 'get'
  match '/forms', to: 'components#forms', via: 'get'
  match '/grid_system', to: 'components#grid_system', via: 'get'
  match '/images', to: 'components#images', via: 'get'
  match '/lookups', to: 'components#lookups', via: 'get'
  match '/advanced_modal', to: 'components#advanced_modal', via: 'get'
  match '/media_objects', to: 'components#media_objects', via: 'get'
  match '/notifications', to: 'components#notifications', via: 'get'
  match '/page_headers', to: 'components#page_headers', via: 'get'
  match '/picklists', to: 'components#picklists', via: 'get'
  match '/pills', to: 'components#pills', via: 'get'
  match '/popovers', to: 'components#popovers', via: 'get'
  match '/spinners', to: 'components#spinners', via: 'get'
  match '/tabs', to: 'components#tabs', via: 'get'
  match '/tiles', to: 'components#tiles', via: 'get'
  match '/tooltips', to: 'components#tooltips', via: 'get'
  match '/trees', to: 'components#trees', via: 'get'
  match '/floats', to: 'components#floats', via: 'get'
  match '/lists', to: 'components#lists', via: 'get'
  match '/scrollable', to: 'components#scrollable', via: 'get'
  match '/text', to: 'components#text', via: 'get'
  match '/themes', to: 'components#themes', via: 'get'
  match '/truncation', to: 'components#truncation', via: 'get'
  match '/visibility', to: 'components#visibility', via: 'get'
  root 'components#activity_timeline'
end
